language: java
jdk:
- oraclejdk8

after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

# use latest java version available instead of travis default
addons:
  apt:
    packages:
      - oracle-java8-installer
